# Generated by Django 5.0.7 on 2024-07-18 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guiasTuristicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=800)),
                ('fecha', models.CharField(max_length=100)),
                ('salida', models.CharField(max_length=100)),
                ('regreso', models.CharField(max_length=100)),
                ('incluye', models.CharField(max_length=255)),
                ('gastosExtra', models.CharField(max_length=300)),
                ('recorrido', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=60)),
                ('imagenes', models.CharField(max_length=75)),
                ('guiaEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiasTuristicos.guias')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPersonas', models.IntegerField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetesTuristicos.paquetes')),
                ('usuarioReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
