# Generated by Django 5.0.7 on 2024-08-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetesTuristicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='total',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
