# Generated by Django 5.0.7 on 2024-08-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetesTuristicos', '0002_reservas_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='total',
            field=models.FloatField(),
        ),
    ]
