# Generated by Django 5.0.7 on 2024-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=600)),
                ('correo', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=25)),
                ('zona', models.CharField(max_length=75)),
                ('fotografia', models.CharField(max_length=75)),
            ],
        ),
    ]
